version: '2'
services:
  mysql:
    image: psbrandt-docker-openmrs-refapp-debian.bintray.io/mysql:2.3.1
    ports:
      - "3306:3306"
    container_name: mysql
    environment:
         - MYSQL_ROOT_PASSWORD=openmrs
         - MYSQL_USER=openmrs
         - MYSQL_PASSWORD=openmrs
  openmrs-refapp-tomcat:
    build: tomcat
    ports:
      - "8080:8080"
      - "5000:5000"
    container_name: openmrs-refapp-tomcat
    links:
      - mysql

  zookeeper:
    image: debezium/zookeeper:${DEBEZIUM_VERSION}
    ports:
     - 2181:2181
     - 2888:2888
     - 3888:3888
  kafka:
    image: debezium/kafka:${DEBEZIUM_VERSION}
    ports:
     - 9092:9092
    links:
     - zookeeper
    environment:
     - ZOOKEEPER_CONNECT=zookeeper:2181
  connect:
    image: debezium/connect:${DEBEZIUM_VERSION}
    ports:
     - 8083:8083
    links:
     - kafka
     - mysql
    environment:
     - BOOTSTRAP_SERVERS=kafka:9092
     - GROUP_ID=1
     - CONFIG_STORAGE_TOPIC=my_connect_configs
     - OFFSET_STORAGE_TOPIC=my_connect_offsets
